//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample1.Models
{
    using System;
    using System.Collections.Generic;
    using Microsoft.AspNetCore.Http;

    public partial class User_Details
    {
        public string Email { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string MobileNumber { get; set; }
        public string ResumeUrl { get; set; }
        public string PhotoUrl { get; set; }
        public IFormFile PhotoPdf { set; get; }
        public IFormFile ResumePdf { get; set; }
    }
}
